// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVSGfqDl2Xq7MPbbr6ufR9wtd4ckjH-o',
    appId: '1:716870704367:web:3a697d0a3b683509648f1a',
    messagingSenderId: '716870704367',
    projectId: 'chats-1f0de',
    authDomain: 'chats-1f0de.firebaseapp.com',
    storageBucket: 'chats-1f0de.appspot.com',
    measurementId: 'G-XEZWDDDX9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHA-crxhA_orItzqtdWdYHuqmRqyk4wWA',
    appId: '1:716870704367:android:6ac7352e60f60842648f1a',
    messagingSenderId: '716870704367',
    projectId: 'chats-1f0de',
    storageBucket: 'chats-1f0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPm4JRRPxB15LweDQPrJLWcuvb7Tn-gPw',
    appId: '1:716870704367:ios:8bb86e6b2910d624648f1a',
    messagingSenderId: '716870704367',
    projectId: 'chats-1f0de',
    storageBucket: 'chats-1f0de.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPm4JRRPxB15LweDQPrJLWcuvb7Tn-gPw',
    appId: '1:716870704367:ios:8bb86e6b2910d624648f1a',
    messagingSenderId: '716870704367',
    projectId: 'chats-1f0de',
    storageBucket: 'chats-1f0de.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDVSGfqDl2Xq7MPbbr6ufR9wtd4ckjH-o',
    appId: '1:716870704367:web:18b3f3394b11b61d648f1a',
    messagingSenderId: '716870704367',
    projectId: 'chats-1f0de',
    authDomain: 'chats-1f0de.firebaseapp.com',
    storageBucket: 'chats-1f0de.appspot.com',
    measurementId: 'G-V5JWQHB3FW',
  );
}
